GET http://localhost:3001/api

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email":"leandro@admin.com",
    "password":"1234"
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"admin2@admin.com",
    "password":"1234"
}

###
